version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./:/go/src/github.com/mwaaas/awsSsh
      - ~/.ssh/:/root/.ssh/
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=eu-west-1